title: Pandora's Box
description: Infection simulation by md2236 and yy2236.
theme: just-the-docs

url: https://md2236_yy2236.github.io
baseurl: ""   

permalink: pretty

defaults:
  - scope:
      path: "docs" 
      type: "pages"
    values:
      layout: "default"
